### ISSUE TITLE
Add TOML configuration.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [cloudy-org/roseate#20]
The toml configuration will be located at `~/.config/cloudy/roseate/config.toml`.

We should have a struct in the application state that allows us to access fields from this config without having to constantly read the file.

I'm also thinking of a feature where it watches the config file for changes with some watchdog implementation and if a change occurs roseate automatically updates to adjust to those changes kind of like hyprland with its config file.

Although I think all of this logic should be in the cirrus tool kit other than in roseate itself so we can reuse the config system in other applications.

**Comment by THEGOLDENPRO** [comment]
Just dropping a quick mock up of the roseate configuration file:
```toml
[image]

[image.loading]
initial.on_main_thread = true
dynamic.on_main_thread = false
```
